version: 3.1.{build}

platform:
  - x32

configuration:
  - Debug

matrix:
  fast_finish: true

os: Visual Studio 2015

install:
  - bin\tools\windows\premake5 vs2015

build:
  parallel: true
  project: traffic3.sln

test_script:
  - test/Debug/traffic3_test.exe -s
  - test/Release/traffic3_text.exe -s
